Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1799, in run
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1799, in run
    pubsub.get_message(ignore_subscribe_messages=True, timeout=sleep_time)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1690, in get_message
    pubsub.get_message(ignore_subscribe_messages=True, timeout=sleep_time)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1690, in get_message
    response = self.parse_response(block=(timeout is None), timeout=timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1542, in parse_response
    response = self.parse_response(block=(timeout is None), timeout=timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1542, in parse_response
    response = self._execute(conn, try_read)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1518, in _execute
    response = self._execute(conn, try_read)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1518, in _execute
    return conn.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    return conn.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1520, in <lambda>
    fail(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1520, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1507, in _disconnect_raise_connect
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1507, in _disconnect_raise_connect
    raise error
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1519, in <lambda>
    raise error
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1519, in <lambda>
    lambda: command(*args, **kwargs),
    lambda: command(*args, **kwargs),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1536, in try_read
    if not conn.can_read(timeout=timeout):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 861, in can_read
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1536, in try_read
    if not conn.can_read(timeout=timeout):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 861, in can_read
    return self._parser.can_read(timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 444, in can_read
    return self._parser.can_read(timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 444, in can_read
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 455, in read_from_socket
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 455, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Traceback (most recent call last):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/magic/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 202, in start_worker
    start_worker(
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 297, in start_worker
    worker.work(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 456, in work
    self.teardown()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1047, in teardown
    self.unsubscribe()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 624, in unsubscribe
    self.pubsub.unsubscribe()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1659, in unsubscribe
    return self.execute_command("UNSUBSCRIBE", *args)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1479, in execute_command
    self._execute(connection, connection.send_command, *args, **kwargs)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1518, in _execute
    return conn.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1520, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1507, in _disconnect_raise_connect
    raise error
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1519, in <lambda>
    lambda: command(*args, **kwargs),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 847, in send_command
    self.send_packed_command(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 817, in send_packed_command
    self.connect()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
2024-09-30 12:43:13,990 Worker rq:worker:548d9d93cbf348818fb36b57bf0fee43: found an unhandled exception, quitting...
Traceback (most recent call last):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1210, in monitor_work_horse
    retpid, ret_val, rusage = self.wait_for_horse()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 951, in wait_for_horse
    pid, stat, rusage = os.wait4(self.horse_pid, 0)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
    raise self._exception('Task exceeded maximum timeout value ({0} seconds)'.format(self._timeout))
rq.timeouts.HorseMonitorTimeoutException: Task exceeded maximum timeout value (30 seconds)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1463, in get_connection
    if connection.can_read():
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 861, in can_read
    return self._parser.can_read(timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 444, in can_read
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 455, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 432, in work
    self.execute_job(job, queue)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1273, in execute_job
    self.monitor_work_horse(job, queue)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1215, in monitor_work_horse
    self.set_current_job_working_time((utcnow() - job.started_at).total_seconds())
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 887, in set_current_job_working_time
    connection.hset(self.key, 'current_job_working_time', current_job_working_time)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/commands/core.py", line 4952, in hset
    return self.execute_command("HSET", name, *items)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1467, in get_connection
    connection.connect()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
Traceback (most recent call last):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/magic/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 202, in start_worker
    start_worker(
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 297, in start_worker
    worker.work(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 456, in work
    self.teardown()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1046, in teardown
    self.register_death()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 832, in register_death
    p.execute()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 2114, in execute
    conn = self.connection_pool.get_connection("MULTI", self.shard_hint)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1457, in get_connection
    connection.connect()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1799, in run
    pubsub.get_message(ignore_subscribe_messages=True, timeout=sleep_time)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1690, in get_message
    response = self.parse_response(block=(timeout is None), timeout=timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1542, in parse_response
    self.run()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1799, in run
    response = self._execute(conn, try_read)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1518, in _execute
    pubsub.get_message(ignore_subscribe_messages=True, timeout=sleep_time)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1690, in get_message
    return conn.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1520, in <lambda>
    response = self.parse_response(block=(timeout is None), timeout=timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1542, in parse_response
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1507, in _disconnect_raise_connect
    response = self._execute(conn, try_read)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1518, in _execute
    raise error
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1519, in <lambda>
    return conn.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1520, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1507, in _disconnect_raise_connect
    lambda: command(*args, **kwargs),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1536, in try_read
    if not conn.can_read(timeout=timeout):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 861, in can_read
    return self._parser.can_read(timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 444, in can_read
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 455, in read_from_socket
    raise error
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1519, in <lambda>
    lambda: command(*args, **kwargs),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1536, in try_read
    if not conn.can_read(timeout=timeout):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 861, in can_read
    return self._parser.can_read(timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 444, in can_read
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 455, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Traceback (most recent call last):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1002, in _connect
Traceback (most recent call last):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 990, in _connect
    raise err
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    rv = self.invoke(ctx)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    click.Group(commands=commands)(prog_name="bench")
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    rv = self.invoke(ctx)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return __callback(*args, **kwargs)
  File "/home/magic/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 202, in start_worker
    start_worker(
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 297, in start_worker
    worker.work(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 456, in work
    self.teardown()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1047, in teardown
    self.unsubscribe()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 624, in unsubscribe
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/magic/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 202, in start_worker
    self.pubsub.unsubscribe()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1659, in unsubscribe
    start_worker(
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 297, in start_worker
    worker.work(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 456, in work
    self.teardown()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1047, in teardown
    return self.execute_command("UNSUBSCRIBE", *args)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1479, in execute_command
    self.unsubscribe()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 624, in unsubscribe
    self.pubsub.unsubscribe()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1659, in unsubscribe
    self._execute(connection, connection.send_command, *args, **kwargs)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1518, in _execute
    return self.execute_command("UNSUBSCRIBE", *args)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1479, in execute_command
    return conn.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1520, in <lambda>
    self._execute(connection, connection.send_command, *args, **kwargs)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1518, in _execute
    return conn.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1507, in _disconnect_raise_connect
    fail(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1520, in <lambda>
    raise error
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1519, in <lambda>
    lambda: command(*args, **kwargs),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 847, in send_command
    self.send_packed_command(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 817, in send_packed_command
    self.connect()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 705, in connect
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1507, in _disconnect_raise_connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
    raise error
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1519, in <lambda>
    lambda: command(*args, **kwargs),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 847, in send_command
    self.send_packed_command(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 817, in send_packed_command
    self.connect()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1799, in run
    self.run()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1799, in run
    pubsub.get_message(ignore_subscribe_messages=True, timeout=sleep_time)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1690, in get_message
    pubsub.get_message(ignore_subscribe_messages=True, timeout=sleep_time)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1690, in get_message
    response = self.parse_response(block=(timeout is None), timeout=timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1542, in parse_response
    response = self.parse_response(block=(timeout is None), timeout=timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1542, in parse_response
    response = self._execute(conn, try_read)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1518, in _execute
    response = self._execute(conn, try_read)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1518, in _execute
    return conn.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    return conn.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1520, in <lambda>
    fail(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1520, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1507, in _disconnect_raise_connect
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1507, in _disconnect_raise_connect
    raise error
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    raise error
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1519, in <lambda>
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1519, in <lambda>
    lambda: command(*args, **kwargs),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1536, in try_read
    lambda: command(*args, **kwargs),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1536, in try_read
    if not conn.can_read(timeout=timeout):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 861, in can_read
    if not conn.can_read(timeout=timeout):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 861, in can_read
    return self._parser.can_read(timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 444, in can_read
    return self._parser.can_read(timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 444, in can_read
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 455, in read_from_socket
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 455, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Traceback (most recent call last):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 699, in connect
Traceback (most recent call last):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    sock = self.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1002, in _connect
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 990, in _connect
    raise err
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    main()
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    click.Group(commands=commands)(prog_name="bench")
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    return self.main(*args, **kwargs)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    rv = self.invoke(ctx)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/magic/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 202, in start_worker
    return __callback(*args, **kwargs)
  File "/home/magic/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 202, in start_worker
    start_worker(
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 297, in start_worker
    start_worker(
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 297, in start_worker
    worker.work(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 456, in work
    worker.work(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 456, in work
    self.teardown()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1047, in teardown
    self.teardown()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1047, in teardown
    self.unsubscribe()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 624, in unsubscribe
    self.unsubscribe()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 624, in unsubscribe
    self.pubsub.unsubscribe()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1659, in unsubscribe
    self.pubsub.unsubscribe()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1659, in unsubscribe
    return self.execute_command("UNSUBSCRIBE", *args)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1479, in execute_command
    return self.execute_command("UNSUBSCRIBE", *args)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1479, in execute_command
    self._execute(connection, connection.send_command, *args, **kwargs)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1518, in _execute
    self._execute(connection, connection.send_command, *args, **kwargs)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1518, in _execute
    return conn.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1520, in <lambda>
    return conn.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1520, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1507, in _disconnect_raise_connect
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1507, in _disconnect_raise_connect
    raise error
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1519, in <lambda>
    lambda: command(*args, **kwargs),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 847, in send_command
    raise error
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1519, in <lambda>
    self.send_packed_command(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 817, in send_packed_command
    self.connect()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 705, in connect
    lambda: command(*args, **kwargs),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 847, in send_command
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
    self.send_packed_command(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 817, in send_packed_command
    self.connect()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
Traceback (most recent call last):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 874, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 493, in read_response
    self.read_from_socket()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 453, in read_from_socket
    bufflen = self._sock.recv_into(self._buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/magic/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 202, in start_worker
    start_worker(
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 297, in start_worker
    worker.work(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 456, in work
Traceback (most recent call last):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 874, in read_response
    self.teardown()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1046, in teardown
    self.register_death()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 832, in register_death
    p.execute()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 2120, in execute
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 493, in read_response
    self.read_from_socket()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 453, in read_from_socket
    bufflen = self._sock.recv_into(self._buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/magic/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 202, in start_worker
    start_worker(
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 297, in start_worker
    worker.work(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 456, in work
    self.teardown()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1046, in teardown
    self.register_death()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 832, in register_death
    p.execute()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 2120, in execute
    return conn.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    return conn.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 2122, in <lambda>
    fail(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 2122, in <lambda>
    lambda error: self._disconnect_raise_reset(conn, error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 2121, in <lambda>
    lambda: execute(conn, stack, raise_on_error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1975, in _execute_transaction
    lambda error: self._disconnect_raise_reset(conn, error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 2121, in <lambda>
    self.parse_response(connection, "_")
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 2060, in parse_response
    lambda: execute(conn, stack, raise_on_error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1975, in _execute_transaction
    result = Redis.parse_response(self, connection, command_name, **options)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1286, in parse_response
    self.parse_response(connection, "_")
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 2060, in parse_response
    response = connection.read_response()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 882, in read_response
    raise ConnectionError(
redis.exceptions.ConnectionError: Error while reading from 127.0.0.1:11000 : (104, 'Connection reset by peer')
    result = Redis.parse_response(self, connection, command_name, **options)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1286, in parse_response
    response = connection.read_response()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 882, in read_response
    raise ConnectionError(
redis.exceptions.ConnectionError: Error while reading from 127.0.0.1:11000 : (104, 'Connection reset by peer')
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2024-09-30 16:09:14,969 Could not connect to Redis instance: Connection closed by server. Retrying in 1 seconds...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2024-09-30 16:09:14,969 Could not connect to Redis instance: Connection closed by server. Retrying in 1 seconds...
    self.run()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1799, in run
    self.run()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1799, in run
    pubsub.get_message(ignore_subscribe_messages=True, timeout=sleep_time)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1690, in get_message
    pubsub.get_message(ignore_subscribe_messages=True, timeout=sleep_time)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1690, in get_message
    response = self.parse_response(block=(timeout is None), timeout=timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1542, in parse_response
    response = self._execute(conn, try_read)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1518, in _execute
    response = self.parse_response(block=(timeout is None), timeout=timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1542, in parse_response
    return conn.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    response = self._execute(conn, try_read)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1518, in _execute
    return conn.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1520, in <lambda>
    fail(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1520, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1507, in _disconnect_raise_connect
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1507, in _disconnect_raise_connect
    raise error
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1519, in <lambda>
    raise error
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1519, in <lambda>
    lambda: command(*args, **kwargs),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1536, in try_read
    lambda: command(*args, **kwargs),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1536, in try_read
    if not conn.can_read(timeout=timeout):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 861, in can_read
    if not conn.can_read(timeout=timeout):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 861, in can_read
    return self._parser.can_read(timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 444, in can_read
    return self._parser.can_read(timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 444, in can_read
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 455, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 455, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Traceback (most recent call last):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 699, in connect
Traceback (most recent call last):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    sock = self.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1002, in _connect
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    raise err
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    exec(code, run_globals)
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    main()
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return self.main(*args, **kwargs)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/magic/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 202, in start_worker
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/magic/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 202, in start_worker
    start_worker(
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 297, in start_worker
    start_worker(
    worker.work(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 456, in work
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 297, in start_worker
    worker.work(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 456, in work
    self.teardown()
    self.teardown()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1047, in teardown
    self.unsubscribe()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 624, in unsubscribe
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1047, in teardown
    self.pubsub.unsubscribe()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1659, in unsubscribe
    self.unsubscribe()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 624, in unsubscribe
    self.pubsub.unsubscribe()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1659, in unsubscribe
    return self.execute_command("UNSUBSCRIBE", *args)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1469, in execute_command
    return self.execute_command("UNSUBSCRIBE", *args)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1469, in execute_command
    self.connection = self.connection_pool.get_connection(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1457, in get_connection
    connection.connect()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 705, in connect
    self.connection = self.connection_pool.get_connection(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1457, in get_connection
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
    connection.connect()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
2024-10-01 12:51:25,817 Could not connect to Redis instance: Connection closed by server. Retrying in 1 seconds...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2024-10-01 12:51:25,828 Could not connect to Redis instance: Connection closed by server. Retrying in 1 seconds...
    self.run()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1799, in run
    self.run()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1799, in run
    pubsub.get_message(ignore_subscribe_messages=True, timeout=sleep_time)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1690, in get_message
    response = self.parse_response(block=(timeout is None), timeout=timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1542, in parse_response
    pubsub.get_message(ignore_subscribe_messages=True, timeout=sleep_time)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1690, in get_message
    response = self.parse_response(block=(timeout is None), timeout=timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1542, in parse_response
    response = self._execute(conn, try_read)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1518, in _execute
    response = self._execute(conn, try_read)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1518, in _execute
    return conn.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    return conn.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1520, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1507, in _disconnect_raise_connect
    raise error
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1519, in <lambda>
    lambda: command(*args, **kwargs),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1536, in try_read
    if not conn.can_read(timeout=timeout):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 861, in can_read
    return self._parser.can_read(timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 444, in can_read
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 455, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    fail(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1520, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1507, in _disconnect_raise_connect
    raise error
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1519, in <lambda>
    lambda: command(*args, **kwargs),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1536, in try_read
    if not conn.can_read(timeout=timeout):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 861, in can_read
    return self._parser.can_read(timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 444, in can_read
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 455, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
2024-10-01 12:51:26,824 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2024-10-01 12:51:26,834 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
Traceback (most recent call last):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 699, in connect
Traceback (most recent call last):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    sock = self.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/magic/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 202, in start_worker
    return self.main(*args, **kwargs)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/magic/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 202, in start_worker
    start_worker(
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 297, in start_worker
    start_worker(
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 297, in start_worker
    worker.work(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 456, in work
    worker.work(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 456, in work
    self.teardown()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1047, in teardown
    self.teardown()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1046, in teardown
    self.unsubscribe()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 624, in unsubscribe
    self.pubsub.unsubscribe()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1659, in unsubscribe
    self.register_death()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 832, in register_death
    p.execute()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 2114, in execute
    return self.execute_command("UNSUBSCRIBE", *args)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1469, in execute_command
    self.connection = self.connection_pool.get_connection(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1457, in get_connection
    conn = self.connection_pool.get_connection("MULTI", self.shard_hint)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1457, in get_connection
    connection.connect()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
    connection.connect()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
Traceback (most recent call last):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
Traceback (most recent call last):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 699, in connect
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/magic/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 202, in start_worker
    start_worker(
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 297, in start_worker
    worker.work(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 456, in work
    sock = self.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/magic/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 202, in start_worker
    start_worker(
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 297, in start_worker
    worker.work(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 456, in work
    self.teardown()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1046, in teardown
    self.register_death()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 832, in register_death
    p.execute()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 2114, in execute
    conn = self.connection_pool.get_connection("MULTI", self.shard_hint)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1457, in get_connection
    connection.connect()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
    self.teardown()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1046, in teardown
    self.register_death()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 832, in register_death
    p.execute()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 2114, in execute
    conn = self.connection_pool.get_connection("MULTI", self.shard_hint)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1457, in get_connection
    connection.connect()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2024-10-01 13:21:02,809 Worker rq:worker:23cf1d242ad84a34abcd279fd953975e: Redis connection timeout, quitting...
2024-10-01 13:21:02,855 Worker rq:worker:e35db0805c5f44d894fa765bb981ec89: Redis connection timeout, quitting...
2024-10-01 13:27:54,218 Worker rq:worker:8310a104b9a24c88ad8fc499b56135d3: Redis connection timeout, quitting...
2024-10-01 13:27:54,246 Worker rq:worker:1c2c957ee6d048fd955d5d64e9c68957: Redis connection timeout, quitting...
Traceback (most recent call last):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/magic/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 202, in start_worker
    start_worker(
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 297, in start_worker
    worker.work(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 456, in work
    self.teardown()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1047, in teardown
    self.unsubscribe()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 624, in unsubscribe
    self.pubsub.unsubscribe()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1659, in unsubscribe
    return self.execute_command("UNSUBSCRIBE", *args)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1469, in execute_command
    self.connection = self.connection_pool.get_connection(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1457, in get_connection
    connection.connect()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
2024-10-01 13:38:14,539 Worker rq:worker:9da8148c3b5d4a538b22705f5fadbc61: Redis connection timeout, quitting...
2024-10-01 13:38:14,574 Worker rq:worker:0eb9ab44783b461c8ab2e89b3e3e5746: Redis connection timeout, quitting...
2024-10-01 13:44:50,611 Worker rq:worker:579c2ed28c074fd3a000a161ca596e56: Redis connection timeout, quitting...
2024-10-01 13:44:50,647 Worker rq:worker:e05d82a38f424a17a2e9ed9b52784e60: Redis connection timeout, quitting...
2024-10-01 13:51:22,666 Worker rq:worker:37f2b69a85794901b98430a2b2003230: Redis connection timeout, quitting...
2024-10-01 13:51:22,765 Worker rq:worker:e5ec0b602a5b43f3a65921ba21b72cf5: Redis connection timeout, quitting...
2024-10-01 13:57:55,891 Worker rq:worker:9f616e4c2ccd4c8ca27a12892bf76b83: Redis connection timeout, quitting...
2024-10-01 13:57:55,892 Worker rq:worker:3b89e997b06445f1b228082d11cc7baf: Redis connection timeout, quitting...
2024-10-01 14:04:28,517 Worker rq:worker:3b43427a9cf64827a5fc665dd11d5524: Redis connection timeout, quitting...
2024-10-01 14:04:28,600 Worker rq:worker:306a45d0728d4b428e7fcd477e9717d4: Redis connection timeout, quitting...
2024-10-01 14:11:01,202 Worker rq:worker:1b7d91cccd8e4d79a0e40ac363ef1d41: Redis connection timeout, quitting...
2024-10-01 14:11:01,208 Worker rq:worker:83c681ae8ad34a50849137d177438934: Redis connection timeout, quitting...
2024-10-01 14:17:35,713 Worker rq:worker:71b2df92130f405fb5e2adbdb0ff2aa7: Redis connection timeout, quitting...
2024-10-01 14:17:35,730 Worker rq:worker:4cdb3026a07a457eaacb88bd6229a3d5: Redis connection timeout, quitting...
2024-10-01 14:24:08,535 Worker rq:worker:29c9159a030e441fb15997a73aa335c0: Redis connection timeout, quitting...
2024-10-01 14:24:08,553 Worker rq:worker:4a7796a8592f43549acda6f0c2809f7c: Redis connection timeout, quitting...
2024-10-01 14:30:41,070 Worker rq:worker:7b29bbd5295d484a8b6952e92797fc30: Redis connection timeout, quitting...
2024-10-01 14:30:41,118 Worker rq:worker:2937d7fb8057438ea8413453e7a97673: Redis connection timeout, quitting...
2024-10-01 14:37:14,616 Worker rq:worker:1d14fb83b30846279b8742e47950d558: Redis connection timeout, quitting...
2024-10-01 14:37:14,735 Worker rq:worker:5af0ecde54ba46379b45bc772f88fcf5: Redis connection timeout, quitting...
2024-10-01 14:43:48,490 Worker rq:worker:ad3a478ff79c411cb4acbde587141ddd: Redis connection timeout, quitting...
2024-10-01 14:43:48,521 Worker rq:worker:127b0fd01059498596039ba394569bc0: Redis connection timeout, quitting...
2024-10-01 14:50:21,605 Worker rq:worker:ba164cca984842e5a254a524a81cb152: Redis connection timeout, quitting...
2024-10-01 14:50:21,653 Worker rq:worker:a5a6c69aa26e49769001ffaa1473db93: Redis connection timeout, quitting...
2024-10-01 14:56:53,331 Worker rq:worker:6b968bc3e13c4add8218452bcead36a7: Redis connection timeout, quitting...
2024-10-01 14:56:53,344 Worker rq:worker:78227fe148504517832f09a45c11b52f: Redis connection timeout, quitting...
2024-10-01 15:03:25,052 Worker rq:worker:580a9497e36947909c7289099f3d424c: Redis connection timeout, quitting...
2024-10-01 15:03:25,082 Worker rq:worker:ba9ca04064884b0b8bf3ed9a8a80f6e3: Redis connection timeout, quitting...
2024-10-01 15:09:55,968 Worker rq:worker:8c280727833347219d8d4299402ecbdc: Redis connection timeout, quitting...
2024-10-01 15:09:55,999 Worker rq:worker:e63f29ec1ef64946a9ed67db3d7f9a2e: Redis connection timeout, quitting...
2024-10-01 15:16:26,673 Worker rq:worker:4b71305c64874135939e26fa6676a6e0: Redis connection timeout, quitting...
2024-10-01 15:16:26,770 Worker rq:worker:475f1e99c3684df8b7e0c613347c4485: Redis connection timeout, quitting...
2024-10-01 15:22:57,268 Worker rq:worker:4fcfc979b0c44814b8823a509b6ac753: Redis connection timeout, quitting...
2024-10-01 15:22:57,280 Worker rq:worker:458494fb61ef4daea7b250de90b8687f: Redis connection timeout, quitting...
2024-10-01 15:29:28,864 Worker rq:worker:2a1937df257f4d6d8242e82d567996d3: Redis connection timeout, quitting...
2024-10-01 15:29:28,954 Worker rq:worker:1f8afc2663c044c8916558076f6263ac: Redis connection timeout, quitting...
2024-10-01 15:36:00,490 Worker rq:worker:f6dc37fffc2945a9aba31f448ee69f1c: Redis connection timeout, quitting...
2024-10-01 15:36:00,559 Worker rq:worker:9625a42baa994d24b6454d0ea5dba2d0: Redis connection timeout, quitting...
2024-10-01 15:42:32,423 Worker rq:worker:305e3faf07a8458891d70d1137af629a: Redis connection timeout, quitting...
2024-10-01 15:42:32,431 Worker rq:worker:8380d7c2f1bb4154bc03078fe205041d: Redis connection timeout, quitting...
2024-10-01 15:49:03,657 Worker rq:worker:fcf44f41733e4763bc6bfebe01193121: Redis connection timeout, quitting...
2024-10-01 15:49:03,712 Worker rq:worker:fcfacb245c5b4a2a8e08b74ef00bc46a: Redis connection timeout, quitting...
2024-10-01 15:55:33,725 Worker rq:worker:68c72f47c44e469d918b506d822d5eee: Redis connection timeout, quitting...
2024-10-01 15:55:33,824 Worker rq:worker:0f480ace5c9e4f029c532c118202e72b: Redis connection timeout, quitting...
2024-10-01 16:02:03,670 Worker rq:worker:c43712762a944aa6baf2b56bba34012c: Redis connection timeout, quitting...
2024-10-01 16:02:03,671 Worker rq:worker:58bb21241442436497dbad1cdcf05222: Redis connection timeout, quitting...
2024-10-01 16:08:33,607 Worker rq:worker:5f803edea4e543219fddee81c59a515b: Redis connection timeout, quitting...
2024-10-01 16:08:33,629 Worker rq:worker:8d07ecf871c5456da4731055a64a11be: Redis connection timeout, quitting...
2024-10-01 16:15:03,567 Worker rq:worker:44b31b9f3dcb4f13b9ef99a4c57045fd: Redis connection timeout, quitting...
2024-10-01 16:15:03,576 Worker rq:worker:07a4dd77266d4c01a03ba0b6dc99c0a3: Redis connection timeout, quitting...
2024-10-01 16:21:33,482 Worker rq:worker:04019aaf0cf947dd95a4b43cb0f7d0f8: Redis connection timeout, quitting...
2024-10-01 16:21:33,513 Worker rq:worker:3e5e41767ce8488e8f5a2d22bcf591e7: Redis connection timeout, quitting...
2024-10-01 16:28:03,362 Worker rq:worker:a75511413a0c499bb6c3f55d38d73d5d: Redis connection timeout, quitting...
2024-10-01 16:28:03,372 Worker rq:worker:ce5c886d387c44d6b034fe6ded2202cf: Redis connection timeout, quitting...
2024-10-01 16:34:32,525 Worker rq:worker:b76a64a5c59243a897e94fce57a74c31: Redis connection timeout, quitting...
2024-10-01 16:34:32,563 Worker rq:worker:217dd8a7b23849c9a13bfbebe49b6cf4: Redis connection timeout, quitting...
2024-10-01 16:41:01,468 Worker rq:worker:18870ba8cd8c4ee6ae94bbe20eadd345: Redis connection timeout, quitting...
2024-10-01 16:41:01,469 Worker rq:worker:8d8d28e19557458d85def10fcc75c37c: Redis connection timeout, quitting...
2024-10-01 16:47:31,515 Worker rq:worker:efdb21481a8c41299628ab6314dd4a7d: Redis connection timeout, quitting...
2024-10-01 16:47:31,538 Worker rq:worker:debd786f76d24219a3e08e8ccace6ed2: Redis connection timeout, quitting...
2024-10-01 16:54:01,349 Worker rq:worker:9f81cc48daa844ea867c9a0b720ea1fe: Redis connection timeout, quitting...
2024-10-01 16:54:01,366 Worker rq:worker:f8edcedb66a84f3a9b63dae58e79425c: Redis connection timeout, quitting...
2024-10-01 17:00:30,182 Worker rq:worker:a28e680e8e4a4cb29976aa40c0c7abb6: Redis connection timeout, quitting...
2024-10-01 17:00:30,208 Worker rq:worker:4a04462a7f94435cbfa7173bf23b6b88: Redis connection timeout, quitting...
2024-10-01 17:06:59,894 Worker rq:worker:a8638a8778d7454ea02561252accf0b1: Redis connection timeout, quitting...
2024-10-01 17:06:59,898 Worker rq:worker:98c56df010034f98b9a642ca92855b57: Redis connection timeout, quitting...
2024-10-01 17:13:28,522 Worker rq:worker:83b8b0578a4a45f9a0bf257a188a3900: Redis connection timeout, quitting...
2024-10-01 17:13:28,529 Worker rq:worker:510ca1df373b4a9993a5bce3ffb812e1: Redis connection timeout, quitting...
2024-10-01 17:19:56,886 Worker rq:worker:16dac01186974d14bd052f8cd62afb27: Redis connection timeout, quitting...
2024-10-01 17:19:56,895 Worker rq:worker:f275e6b68d82475ba8e2d4c938e31078: Redis connection timeout, quitting...
2024-10-01 17:26:25,174 Worker rq:worker:96926129f0b24370b602f327e4092bcb: Redis connection timeout, quitting...
2024-10-01 17:26:25,251 Worker rq:worker:3d8c30e7091041d3a54b8f302f694ade: Redis connection timeout, quitting...
2024-10-01 17:32:53,979 Worker rq:worker:284752af08a24bd5be9b32f9048e5f07: Redis connection timeout, quitting...
2024-10-01 17:32:54,012 Worker rq:worker:e41c8f73181e49c9b8c0a7a459f0a4f3: Redis connection timeout, quitting...
2024-10-01 17:39:22,931 Worker rq:worker:5bd3ae78e4d74bfbb7e95e484ea5d85f: Redis connection timeout, quitting...
2024-10-01 17:39:22,933 Worker rq:worker:245543cc7539409a82b2f0f1d4da4d6d: Redis connection timeout, quitting...
2024-10-01 17:45:51,779 Worker rq:worker:bae85c119891401dada278a10b039a0d: Redis connection timeout, quitting...
2024-10-01 17:45:51,813 Worker rq:worker:ab5e0d0a04654d46861eb6e93e655190: Redis connection timeout, quitting...
2024-10-01 17:52:21,097 Worker rq:worker:c6d8baed2fae4fbeb540e828a7b01384: Redis connection timeout, quitting...
2024-10-01 17:52:21,111 Worker rq:worker:fc0ea33a8edd400cb6e3f4b80e7790cf: Redis connection timeout, quitting...
2024-10-01 17:58:50,612 Worker rq:worker:690c9e0f51854881a2417a5b8f8767ad: Redis connection timeout, quitting...
2024-10-01 17:58:50,709 Worker rq:worker:bde4f4486a02448cb4d7c6900d28f258: Redis connection timeout, quitting...
2024-10-01 18:05:19,584 Worker rq:worker:a79464184fda4961ae278667270b6b06: Redis connection timeout, quitting...
2024-10-01 18:05:19,627 Worker rq:worker:dd3a879799874384a3e590bdd4724e90: Redis connection timeout, quitting...
2024-10-01 18:11:48,643 Worker rq:worker:8c1fb629aab742d78c78b4bfd309211f: Redis connection timeout, quitting...
2024-10-01 18:11:48,694 Worker rq:worker:e9afb2f5b2874aa0a91fc3d0c8e44650: Redis connection timeout, quitting...
2024-10-01 18:18:18,874 Worker rq:worker:f5c95394f1134abf8a70901017142ad0: Redis connection timeout, quitting...
2024-10-01 18:18:19,006 Worker rq:worker:7a15a26d80db44f486b052a00c80895c: Redis connection timeout, quitting...
2024-10-01 18:24:47,882 Worker rq:worker:7c06fed3569746659875b1292f0be31d: Redis connection timeout, quitting...
2024-10-01 18:24:47,905 Worker rq:worker:2e94584b7617408aad8fdb1127fb2f34: Redis connection timeout, quitting...
2024-10-01 18:31:15,535 Worker rq:worker:cd14b1c9ae804fffa34475ba54f41aa3: Redis connection timeout, quitting...
2024-10-01 18:31:15,543 Worker rq:worker:8e43a3ceffe74a1b9511f9ee1ad60b93: Redis connection timeout, quitting...
2024-10-01 18:37:42,347 Worker rq:worker:9efbab6c68d148f9a6bcbca6b566b7c2: Redis connection timeout, quitting...
2024-10-01 18:37:42,429 Worker rq:worker:aaffd7de89ab42b0927ed8933adef621: Redis connection timeout, quitting...
2024-10-01 18:44:09,668 Worker rq:worker:7421fc09f1bc471ea1c633253840a2ec: Redis connection timeout, quitting...
2024-10-01 18:44:09,741 Worker rq:worker:06fbebe19d6e4e1cb077c988565b1347: Redis connection timeout, quitting...
Traceback (most recent call last):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 874, in read_response
Traceback (most recent call last):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 874, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 493, in read_response
    self.read_from_socket()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 453, in read_from_socket
    bufflen = self._sock.recv_into(self._buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1799, in run
    return self.main(*args, **kwargs)
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 493, in read_response
    self.read_from_socket()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 453, in read_from_socket
    bufflen = self._sock.recv_into(self._buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    return _process_result(sub_ctx.command.invoke(sub_ctx))
    main()
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/magic/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 202, in start_worker
    return _process_result(sub_ctx.command.invoke(sub_ctx))
    self.run()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1799, in run
    pubsub.get_message(ignore_subscribe_messages=True, timeout=sleep_time)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1690, in get_message
    response = self.parse_response(block=(timeout is None), timeout=timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1542, in parse_response
    response = self._execute(conn, try_read)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1518, in _execute
    return conn.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
    start_worker(
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 297, in start_worker
    worker.work(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 456, in work
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
    fail(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1520, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1507, in _disconnect_raise_connect
    raise error
  File "/home/magic/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 202, in start_worker
    start_worker(
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 297, in start_worker
    worker.work(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1519, in <lambda>
    lambda: command(*args, **kwargs),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 456, in work
    self.teardown()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1046, in teardown
    self.register_death()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 832, in register_death
    p.execute()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 2120, in execute
    return conn.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 2122, in <lambda>
    lambda error: self._disconnect_raise_reset(conn, error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 2121, in <lambda>
    pubsub.get_message(ignore_subscribe_messages=True, timeout=sleep_time)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1690, in get_message
    response = self.parse_response(block=(timeout is None), timeout=timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1542, in parse_response
    response = self._execute(conn, try_read)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1518, in _execute
    return conn.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1520, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1507, in _disconnect_raise_connect
    raise error
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1519, in <lambda>
    lambda: command(*args, **kwargs),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1536, in try_read
    if not conn.can_read(timeout=timeout):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 861, in can_read
    return self._parser.can_read(timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 444, in can_read
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 455, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1536, in try_read
    if not conn.can_read(timeout=timeout):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 861, in can_read
    return self._parser.can_read(timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 444, in can_read
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 455, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    self.teardown()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1046, in teardown
    self.register_death()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 832, in register_death
    p.execute()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 2120, in execute
    return conn.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 2122, in <lambda>
    lambda: execute(conn, stack, raise_on_error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1975, in _execute_transaction
    lambda error: self._disconnect_raise_reset(conn, error),
    self.parse_response(connection, "_")
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 2060, in parse_response
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    result = Redis.parse_response(self, connection, command_name, **options)
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 2121, in <lambda>
    lambda: execute(conn, stack, raise_on_error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1286, in parse_response
    response = connection.read_response()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1975, in _execute_transaction
    self.parse_response(connection, "_")
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 882, in read_response
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 2060, in parse_response
    result = Redis.parse_response(self, connection, command_name, **options)
    raise ConnectionError(
redis.exceptions.ConnectionError: Error while reading from 127.0.0.1:11000 : (104, 'Connection reset by peer')
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1286, in parse_response
    response = connection.read_response()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 882, in read_response
    raise ConnectionError(
redis.exceptions.ConnectionError: Error while reading from 127.0.0.1:11000 : (104, 'Connection reset by peer')
2024-10-01 18:57:38,902 Worker rq:worker:1daaa52f5db54184948e151ab34d56dc: Redis connection timeout, quitting...
2024-10-01 18:57:38,951 Worker rq:worker:fa80b8308796403fa4754911e507bb08: Redis connection timeout, quitting...
2024-10-01 19:04:09,186 Worker rq:worker:67af461e960445dd839a5bfaa550a702: Redis connection timeout, quitting...
2024-10-01 19:04:09,238 Worker rq:worker:08d83e6102124653b5dca5b008672a6f: Redis connection timeout, quitting...
2024-10-01 19:10:37,681 Worker rq:worker:d646b9d95b804b30a2bfea3a676ac10e: Redis connection timeout, quitting...
2024-10-01 19:10:37,682 Worker rq:worker:419314f9426e48878ee48ba29f35ab40: Redis connection timeout, quitting...
2024-10-01 19:17:04,392 Worker rq:worker:65a44ca8ba4544baa2f953cf1caf1d48: Redis connection timeout, quitting...
2024-10-01 19:17:04,401 Worker rq:worker:cc0d5dae6cb344a5a91a53ee56418916: Redis connection timeout, quitting...
2024-10-01 19:23:30,643 Worker rq:worker:0d2caa7f421949978ea61d0664cc0b08: Redis connection timeout, quitting...
2024-10-01 19:23:30,652 Worker rq:worker:610ee42bf6654c58ac2545ed4eb537c9: Redis connection timeout, quitting...
2024-10-01 19:29:57,075 Worker rq:worker:29f9150e0c0c4ca7b705caddf7d20375: Redis connection timeout, quitting...
2024-10-01 19:29:57,097 Worker rq:worker:820bc87929bf4140bb19747a4ec9d1d4: Redis connection timeout, quitting...
2024-10-01 19:36:23,980 Worker rq:worker:17d5f0931ed54f54992d742c5aa9489f: Redis connection timeout, quitting...
2024-10-01 19:36:23,996 Worker rq:worker:aa39bc710cce48c1a267974ccaca1335: Redis connection timeout, quitting...
2024-10-01 19:42:51,523 Worker rq:worker:35d7619e86c24c05860698368b7e7c7b: Redis connection timeout, quitting...
2024-10-01 19:42:51,607 Worker rq:worker:ec8aae7f7df343e0a2ef7a0a7f874abc: Redis connection timeout, quitting...
2024-10-01 19:49:17,590 Worker rq:worker:62d7257f53b646f4a4cb83b4597535e2: Redis connection timeout, quitting...
2024-10-01 19:49:17,631 Worker rq:worker:be9b194690be492d9f3a55b093589d81: Redis connection timeout, quitting...
2024-10-01 19:55:43,186 Worker rq:worker:d3855daee8ff4fa7944831b119624ae2: Redis connection timeout, quitting...
2024-10-01 19:55:43,248 Worker rq:worker:9cdf80f48b9d4a5982437105b81017ee: Redis connection timeout, quitting...
2024-10-01 20:02:11,172 Worker rq:worker:30bed5a329f64faea3948b199f30cfb4: Redis connection timeout, quitting...
2024-10-01 20:02:11,218 Worker rq:worker:8493627908d641dcb9d12c801a27bb94: Redis connection timeout, quitting...
2024-10-01 20:08:36,179 Worker rq:worker:dbcd73db79104d379f08d89828b06bda: Redis connection timeout, quitting...
2024-10-01 20:08:36,189 Worker rq:worker:9e09d8c135c942978cb66f3897dfa6a3: Redis connection timeout, quitting...
2024-10-01 20:15:01,040 Worker rq:worker:b68fbc95073a41e180ac91e321609809: Redis connection timeout, quitting...
2024-10-01 20:15:01,132 Worker rq:worker:0ef81ca27d7e4d25b27a7d3476dff69a: Redis connection timeout, quitting...
2024-10-01 20:21:26,446 Worker rq:worker:7dcf9118be5d437c924f4e4cb29dca0c: Redis connection timeout, quitting...
2024-10-01 20:21:26,471 Worker rq:worker:8842c6be4c494abaa7a2dae97b88e306: Redis connection timeout, quitting...
2024-10-01 20:27:51,224 Worker rq:worker:73cd853045254690afde184512b7bc5d: Redis connection timeout, quitting...
2024-10-01 20:27:51,293 Worker rq:worker:961b7d75a49347f3b36e88f2107d2d8b: Redis connection timeout, quitting...
2024-10-01 20:34:19,450 Worker rq:worker:5b96ef72fcfa44b5a010df4c61f30e23: Redis connection timeout, quitting...
2024-10-01 20:34:19,531 Worker rq:worker:1220e13322704d0a90734519a1803382: Redis connection timeout, quitting...
2024-10-01 20:40:45,977 Worker rq:worker:6f7ae924f41b44f280accda378a21e26: Redis connection timeout, quitting...
2024-10-01 20:40:46,022 Worker rq:worker:4421d44a7b42463b872662356d1920cf: Redis connection timeout, quitting...
2024-10-01 20:47:11,470 Worker rq:worker:0d67e9ef26b84d1b87be43182368ede0: Redis connection timeout, quitting...
2024-10-01 20:47:11,470 Worker rq:worker:a06c08a045c2403dbe586cf8d1559e0b: Redis connection timeout, quitting...
2024-10-01 20:53:36,883 Worker rq:worker:6050a4778e4245cf839bec3113071532: Redis connection timeout, quitting...
2024-10-01 20:53:36,923 Worker rq:worker:7152e60bb97d4d8da7aef8725b569fd8: Redis connection timeout, quitting...
2024-10-01 21:00:01,234 Worker rq:worker:f5a7c143d4384c738ecd509fad85b776: Redis connection timeout, quitting...
2024-10-01 21:00:01,263 Worker rq:worker:137809de26164d6c8e8211b908374793: Redis connection timeout, quitting...
2024-10-01 21:06:26,116 Worker rq:worker:92f487a7c93942cbace37f9664ca1ae6: Redis connection timeout, quitting...
2024-10-01 21:06:26,125 Worker rq:worker:9c8afecbf16e46638d243ec61db42178: Redis connection timeout, quitting...
2024-10-01 21:12:49,763 Worker rq:worker:13087169e9894b64bf9ef31001cfdca5: Redis connection timeout, quitting...
2024-10-01 21:12:49,824 Worker rq:worker:41138472096049478b6f00c5d4986279: Redis connection timeout, quitting...
2024-10-01 21:19:16,532 Worker rq:worker:7daff2bda929454994c7ab9e07960ad8: Redis connection timeout, quitting...
2024-10-01 21:19:16,581 Worker rq:worker:04e53cc3713d4310bb61d73d766a4572: Redis connection timeout, quitting...
2024-10-01 21:25:41,224 Worker rq:worker:5a51a9b86fda47fbb22f406acac27bb6: Redis connection timeout, quitting...
2024-10-01 21:25:41,377 Worker rq:worker:954499c122ab4aa1b4be7449cea3eaad: Redis connection timeout, quitting...
2024-10-01 21:32:05,686 Worker rq:worker:83a9c62280ca4d9bb1163ce551a38114: Redis connection timeout, quitting...
2024-10-01 21:32:05,709 Worker rq:worker:a9ea1fd38f9447358de3371c5184287c: Redis connection timeout, quitting...
2024-10-01 21:38:31,042 Worker rq:worker:9ce72b64e53a4140979408883fb29934: Redis connection timeout, quitting...
2024-10-01 21:38:31,045 Worker rq:worker:16ba93bc3e0c4d1e9b729bd1da917483: Redis connection timeout, quitting...
2024-10-01 21:44:55,474 Worker rq:worker:799219da0ef64307b8bcdde525efb88a: Redis connection timeout, quitting...
2024-10-01 21:44:55,478 Worker rq:worker:069842d208f84057864aaf17df3ed3cf: Redis connection timeout, quitting...
2024-10-01 21:51:18,670 Worker rq:worker:36e3ebfaca884271821d571a5111ec1c: Redis connection timeout, quitting...
2024-10-01 21:51:18,713 Worker rq:worker:c7b94f4145fc4b0eb493b79e760dfbb1: Redis connection timeout, quitting...
2024-10-01 21:57:42,866 Worker rq:worker:3cf6835ce57b4dfc964937461540ccee: Redis connection timeout, quitting...
2024-10-01 21:57:42,872 Worker rq:worker:dac9c8754eb94a7aaa004b8665754075: Redis connection timeout, quitting...
2024-10-01 22:04:07,034 Worker rq:worker:d31ee8d301b74b4fa4a52c322626938b: Redis connection timeout, quitting...
2024-10-01 22:04:07,049 Worker rq:worker:ebdd6ce08d794c9b81fed0df35ef431e: Redis connection timeout, quitting...
2024-10-01 22:10:28,449 Worker rq:worker:5a645c57976f4d75a69f16732a59c813: Redis connection timeout, quitting...
2024-10-01 22:10:28,451 Worker rq:worker:349450d68e3b499f93f567842becd05f: Redis connection timeout, quitting...
2024-10-01 22:16:52,879 Worker rq:worker:35547e2b1e9c48e4a397600cc595effb: Redis connection timeout, quitting...
2024-10-01 22:16:52,892 Worker rq:worker:9215c061837c4ac8bda69770912e1a22: Redis connection timeout, quitting...
2024-10-01 22:23:15,624 Worker rq:worker:580f402951eb484d8220199b6b9b6a34: Redis connection timeout, quitting...
2024-10-01 22:23:15,740 Worker rq:worker:bda01edfc3db451aba9960fdda07bbaa: Redis connection timeout, quitting...
2024-10-01 22:29:40,206 Worker rq:worker:a4eda21d6e2b42fe84d01543def8cae9: Redis connection timeout, quitting...
2024-10-01 22:29:40,231 Worker rq:worker:3de7c6e10f2041fa920f17563284832c: Redis connection timeout, quitting...
2024-10-01 22:36:02,865 Worker rq:worker:dbd7be074d0a4cac9190ee89098726e4: Redis connection timeout, quitting...
2024-10-01 22:36:02,868 Worker rq:worker:454e1a7f93d8430598ee741a3d42c2ee: Redis connection timeout, quitting...
2024-10-01 22:42:25,942 Worker rq:worker:f27ec2e316d544eaa77fa3945de013fa: Redis connection timeout, quitting...
2024-10-01 22:42:25,975 Worker rq:worker:2111c1fc75f94edaa2c8880194480014: Redis connection timeout, quitting...
2024-10-01 22:48:48,939 Worker rq:worker:9d70fedb30ef49dbac417d1f11cfba18: Redis connection timeout, quitting...
2024-10-01 22:48:48,957 Worker rq:worker:cfb207e9b74c4141bb8ba68257a29678: Redis connection timeout, quitting...
2024-10-01 22:55:11,420 Worker rq:worker:4153aafad5f34defad6a6a8bde06bac5: Redis connection timeout, quitting...
2024-10-01 22:55:11,509 Worker rq:worker:445e8aabdc004d439deb63e2c678f9a0: Redis connection timeout, quitting...
2024-10-01 23:01:34,817 Worker rq:worker:dc7fb42b6a704ee3b8df6c1cc60287ac: Redis connection timeout, quitting...
2024-10-01 23:01:34,830 Worker rq:worker:9edfc88cd764425a9eb4a54162a621d4: Redis connection timeout, quitting...
2024-10-01 23:07:56,906 Worker rq:worker:49970e7e2601491bb8e8cbd115174e20: Redis connection timeout, quitting...
2024-10-01 23:07:56,991 Worker rq:worker:d52b5d4cab0f4a0a93fee690447c90e4: Redis connection timeout, quitting...
2024-10-01 23:14:20,654 Worker rq:worker:e6abfce0ccce435797d04c0f246e2cbf: Redis connection timeout, quitting...
2024-10-01 23:14:20,749 Worker rq:worker:e2e4f18e9feb49748038078939f9a8c8: Redis connection timeout, quitting...
2024-10-01 23:20:42,075 Worker rq:worker:a53277b4b9ba4a1f9692c09f23a33675: Redis connection timeout, quitting...
2024-10-01 23:20:42,130 Worker rq:worker:74956625e3a14c5fa27a7e9c4e6d7e47: Redis connection timeout, quitting...
2024-10-02 14:30:28,223 Worker rq:worker:c299c4bdfea448f28ddeaa5afbd5803d: Redis connection timeout, quitting...
2024-10-02 14:30:28,233 Worker rq:worker:dd31a2b5c0bf478e94f4c24cf75d0b50: Redis connection timeout, quitting...
2024-10-02 14:37:23,178 Worker rq:worker:6b63fb0addcb4f14893e6428ee2eafc0: Redis connection timeout, quitting...
2024-10-02 14:37:23,237 Worker rq:worker:88e4bdd555904753a96a559d180e6090: Redis connection timeout, quitting...
2024-10-02 14:44:14,024 Worker rq:worker:cadd825a37844396bdeee5572b5aac79: Redis connection timeout, quitting...
2024-10-02 14:44:14,049 Worker rq:worker:645dc4aeeeb54133a5a498277cabb6e7: Redis connection timeout, quitting...
2024-10-02 14:51:02,999 Worker rq:worker:0d518325315241fd92bdc73d23d4c10f: Redis connection timeout, quitting...
2024-10-02 14:51:03,001 Worker rq:worker:6d4efe9c14fc42769b052f2b7315249c: Redis connection timeout, quitting...
2024-10-02 14:57:52,508 Worker rq:worker:99cc5b0ead224a3d8541fd77beb7d645: Redis connection timeout, quitting...
2024-10-02 14:57:52,512 Worker rq:worker:3cb9b36702554969a0d9e958b26f1a25: Redis connection timeout, quitting...
2024-10-02 15:04:42,513 Worker rq:worker:e11803b5dbc442bbb02c877750594e7c: Redis connection timeout, quitting...
2024-10-02 15:04:42,537 Worker rq:worker:b94ecfe1966543c18ce6f0c0c8ca6003: Redis connection timeout, quitting...
2024-10-02 15:11:32,222 Worker rq:worker:b6e5fb5a9b5c400c849b4e33798598ba: Redis connection timeout, quitting...
2024-10-02 15:11:32,236 Worker rq:worker:26e6d49684f24105a1e05f7191c48d19: Redis connection timeout, quitting...
2024-10-02 15:18:20,453 Worker rq:worker:4418625493504f698c69a6d7e36a52ce: Redis connection timeout, quitting...
2024-10-02 15:18:20,481 Worker rq:worker:39c472931a064717a96ca494720c863a: Redis connection timeout, quitting...
2024-10-02 15:25:09,519 Worker rq:worker:af726b8386994709b0a3e71293afe187: Redis connection timeout, quitting...
2024-10-02 15:25:09,597 Worker rq:worker:79d360109be94b9cadea64fb9242143c: Redis connection timeout, quitting...
2024-10-02 15:31:57,395 Worker rq:worker:27bb424b86084e98833e327d755d77fa: Redis connection timeout, quitting...
2024-10-02 15:31:57,408 Worker rq:worker:472f8c6c713a4eb7bf9326479d69504f: Redis connection timeout, quitting...
2024-10-02 15:38:45,757 Worker rq:worker:00b0f2cbf2bf441eb85ae89d1a75a474: Redis connection timeout, quitting...
2024-10-02 15:38:45,849 Worker rq:worker:34e770491dc248889e6091c8ace0672c: Redis connection timeout, quitting...
2024-10-02 15:45:34,320 Worker rq:worker:1a71bbd995964fb0978c2de17f8a0e68: Redis connection timeout, quitting...
2024-10-02 15:45:34,370 Worker rq:worker:028154201ba24353aeed4c9b0db79278: Redis connection timeout, quitting...
2024-10-02 15:52:22,600 Worker rq:worker:705f63a2f7bc41be965af37ea3f5644c: Redis connection timeout, quitting...
2024-10-02 15:52:22,618 Worker rq:worker:0562fdecacc344be811b471009f47b0b: Redis connection timeout, quitting...
2024-10-02 15:59:10,524 Worker rq:worker:d8d4e4c3e1e94f229541fc59926468ee: Redis connection timeout, quitting...
2024-10-02 15:59:10,544 Worker rq:worker:3add65cf5c894f29b3762ea6d876001a: Redis connection timeout, quitting...
2024-10-02 16:05:58,531 Worker rq:worker:4b3a558da09e4b5b948fa9577679a767: Redis connection timeout, quitting...
2024-10-02 16:05:58,536 Worker rq:worker:bb85219473e14f998dae5c8b57dbe8e9: Redis connection timeout, quitting...
2024-10-02 16:12:41,512 Worker rq:worker:4d7f4553e7574efebf39a222ee9a0c8d: Redis connection timeout, quitting...
2024-10-02 16:12:42,124 Worker rq:worker:0b5eb47e994a4a649e48cad02f4a3274: Redis connection timeout, quitting...
2024-10-02 16:19:24,807 Worker rq:worker:5d304a79c9324b9297efb3aeffcc1d63: Redis connection timeout, quitting...
2024-10-02 16:19:25,438 Worker rq:worker:f94c46c86c2342019d870827039c5cd3: Redis connection timeout, quitting...
2024-10-02 16:26:11,518 Worker rq:worker:2b9a61f24e2146bd8e5820a3c6aaf72b: Redis connection timeout, quitting...
2024-10-02 16:26:11,571 Worker rq:worker:27aa738c17fb484aa1bc304ff83aed17: Redis connection timeout, quitting...
2024-10-02 16:32:57,556 Worker rq:worker:f7d076ea62e447358c92e0cfbb4be6ba: Redis connection timeout, quitting...
2024-10-02 16:32:57,570 Worker rq:worker:ec58c0c26a554ef2ae3ddcf00b7984e5: Redis connection timeout, quitting...
2024-10-02 16:39:39,853 Worker rq:worker:66a3a881f00e46949522fcb36948dd36: Redis connection timeout, quitting...
2024-10-02 16:39:40,410 Worker rq:worker:432e13dd423343e4b0f572297a36e2d4: Redis connection timeout, quitting...
2024-10-02 16:46:22,184 Worker rq:worker:c1fe8648b26040838b9d775f4368550a: Redis connection timeout, quitting...
2024-10-02 16:46:22,856 Worker rq:worker:6a4de768b1c34c329459e1f8dbb7238a: Redis connection timeout, quitting...
2024-10-02 16:53:04,447 Worker rq:worker:0a2c887b25c44c95a7466cc41be3f99b: Redis connection timeout, quitting...
2024-10-02 16:53:04,979 Worker rq:worker:d7fc52a045f34056a2117318aa6a0981: Redis connection timeout, quitting...
2024-10-02 16:59:50,339 Worker rq:worker:20c7c3dd827548fc90d76dcc76a1bdde: Redis connection timeout, quitting...
2024-10-02 16:59:50,379 Worker rq:worker:d82e6a2194c347efa2097fcde30263a9: Redis connection timeout, quitting...
2024-10-02 17:06:35,313 Worker rq:worker:4e9ce8c0b4364315adcd6c56d362f856: Redis connection timeout, quitting...
2024-10-02 17:06:35,332 Worker rq:worker:0eea0371a29342b1a6bb376fae72dc44: Redis connection timeout, quitting...
2024-10-02 17:13:21,330 Worker rq:worker:abccc0e683184093b27b48e00c4a921f: Redis connection timeout, quitting...
2024-10-02 17:13:21,335 Worker rq:worker:a885fe1f3fc64c0cb71ba9bb08dc374a: Redis connection timeout, quitting...
2024-10-02 17:20:06,954 Worker rq:worker:7830768cf1f745fd81e489d6cf43915d: Redis connection timeout, quitting...
2024-10-02 17:20:06,993 Worker rq:worker:fb4c556d98c149ba8ee1ffe1c013185e: Redis connection timeout, quitting...
2024-10-02 17:26:51,398 Worker rq:worker:b328d022d6634eb8b96cf0ef1e677f35: Redis connection timeout, quitting...
2024-10-02 17:26:51,403 Worker rq:worker:5b707712178e4901bbe1b01b19e0b90f: Redis connection timeout, quitting...
2024-10-02 17:33:35,699 Worker rq:worker:2ad023477dc348e599b5ddfe38caeca1: Redis connection timeout, quitting...
2024-10-02 17:33:35,708 Worker rq:worker:c23d9de8f0dd43588fa10befd9e28587: Redis connection timeout, quitting...
2024-10-02 17:40:19,527 Worker rq:worker:baf72ff9a81a429aae5a748ca8f34e0c: Redis connection timeout, quitting...
2024-10-02 17:40:19,563 Worker rq:worker:d46d62f05e054010a01cb1a38b7a8516: Redis connection timeout, quitting...
2024-10-02 17:47:04,389 Worker rq:worker:0dbe25297e5349c1aa9b9eb4e2c51b46: Redis connection timeout, quitting...
2024-10-02 17:47:04,405 Worker rq:worker:398aa1a2dd7a4c0b8d9c91ae7543b0f4: Redis connection timeout, quitting...
2024-10-02 17:53:47,889 Worker rq:worker:0d07dd114f284ee7bb92031eeab373d9: Redis connection timeout, quitting...
2024-10-02 17:53:47,890 Worker rq:worker:429adde8e5bf48148541582d836c4c02: Redis connection timeout, quitting...
2024-10-02 18:00:32,213 Worker rq:worker:de428642c1ba4deb90b8e2064372bc17: Redis connection timeout, quitting...
2024-10-02 18:00:32,261 Worker rq:worker:edd71decfc6b48ad865d1d4ad1fa9eea: Redis connection timeout, quitting...
2024-10-02 18:07:11,745 Worker rq:worker:b857f595589c4545ae802a123435e0ae: Redis connection timeout, quitting...
2024-10-02 18:07:11,801 Worker rq:worker:acdfc4cd7f2b4903a2331fea927a17bc: Redis connection timeout, quitting...
2024-10-02 18:13:54,853 Worker rq:worker:8c0ccda3c4a144b1ac07fd106e8b7dc8: Redis connection timeout, quitting...
2024-10-02 18:13:54,858 Worker rq:worker:5b6abaa3108e426f9a024cce12304fc0: Redis connection timeout, quitting...
2024-10-02 18:20:33,957 Worker rq:worker:1fb5af1d743f4c9fb0dd998f2540a058: Redis connection timeout, quitting...
2024-10-02 18:20:34,537 Worker rq:worker:1aadc2012b8c4e18bd7485c7536180b7: Redis connection timeout, quitting...
2024-10-02 18:27:17,657 Worker rq:worker:9deca583626041a886f847825d985df3: Redis connection timeout, quitting...
2024-10-02 18:27:17,665 Worker rq:worker:41ff53e22a0b46bc93c22c386b84beec: Redis connection timeout, quitting...
2024-10-02 18:33:59,721 Worker rq:worker:468d03044ab7464c99797821b5e4c2d4: Redis connection timeout, quitting...
2024-10-02 18:33:59,745 Worker rq:worker:e572214fe4e24b0b89a52d6feeae19f3: Redis connection timeout, quitting...
2024-10-02 18:40:42,871 Worker rq:worker:2af51d754f64493a8a471226db15f552: Redis connection timeout, quitting...
2024-10-02 18:40:42,888 Worker rq:worker:567e590954fd466c8f91b087145c21aa: Redis connection timeout, quitting...
2024-10-02 18:47:24,831 Worker rq:worker:723a31468ac64beba57b8824de161c1f: Redis connection timeout, quitting...
2024-10-02 18:47:24,926 Worker rq:worker:2e801e4635d64fc1aa29f454b421ff2f: Redis connection timeout, quitting...
2024-10-02 18:54:02,836 Worker rq:worker:879fb657b2404b999ccf31f40b34f90c: Redis connection timeout, quitting...
2024-10-02 18:54:03,474 Worker rq:worker:f6db6846518343ae80053b29692006e9: Redis connection timeout, quitting...
2024-10-02 19:00:45,323 Worker rq:worker:2aaabd2ce9794d25b996919f1d10a4ac: Redis connection timeout, quitting...
2024-10-02 19:00:45,326 Worker rq:worker:4ee0f84f7453409f9f2a889c7ca725eb: Redis connection timeout, quitting...
2024-10-03 09:55:41,643 Worker rq:worker:fd0a84eb5441417ab2e196e71771c0ef: Redis connection timeout, quitting...
2024-10-03 10:02:27,813 Worker rq:worker:c64c41fa814c4a77bfa5a9cd31d588ca: Redis connection timeout, quitting...
2024-10-03 10:02:37,289 Worker rq:worker:63554cc7d647463c844e81b4e541c819: Redis connection timeout, quitting...
2024-10-03 10:09:30,772 Worker rq:worker:494cece3727941acb8a1232157d144c6: Redis connection timeout, quitting...
2024-10-03 10:16:13,633 Worker rq:worker:b7c8c96316474eb1848c18e7e381b102: Redis connection timeout, quitting...
2024-10-03 10:16:22,385 Worker rq:worker:b8783645092648199957748da0d915d3: Redis connection timeout, quitting...
2024-10-03 10:23:03,216 Worker rq:worker:49c42fc3d5df4efe85971aa7b151036f: Redis connection timeout, quitting...
2024-10-03 10:23:08,070 Worker rq:worker:19a0302528f74bd88943d62851ee41d5: Redis connection timeout, quitting...
2024-10-03 10:29:52,759 Worker rq:worker:17e7a3392bed462bac657ac478b88a29: Redis connection timeout, quitting...
2024-10-03 10:29:54,531 Worker rq:worker:05f162557e334104abaa3ee34443de1e: Redis connection timeout, quitting...
2024-10-03 10:36:38,010 Worker rq:worker:7108c37c41da40ca9feadfca13065b73: Redis connection timeout, quitting...
2024-10-03 10:36:39,779 Worker rq:worker:288544c617ff4f79906a9d5d200f9637: Redis connection timeout, quitting...
2024-10-03 10:43:27,028 Worker rq:worker:831c946536ef4ce49ab4a9b632b82fb5: Redis connection timeout, quitting...
2024-10-03 10:43:27,107 Worker rq:worker:91558e11079c4d9ca944d3e0dce788f9: Redis connection timeout, quitting...
2024-10-03 10:55:08,662 Worker rq:worker:5844cc3b7b344f15a1783d3663145a73: Redis connection timeout, quitting...
2024-10-03 10:55:08,666 Worker rq:worker:a11e843b764d4d0286870c356986872d: Redis connection timeout, quitting...
2024-10-03 11:01:57,215 Worker rq:worker:aa13c0e0daa14eb08e433c240e15f44b: Redis connection timeout, quitting...
2024-10-03 11:01:57,221 Worker rq:worker:cfe07baa1f5f45c0a250d2325c62a33f: Redis connection timeout, quitting...
2024-10-03 11:08:44,379 Worker rq:worker:ca9ce8e5cf0d495bbd31b1139a26a9eb: Redis connection timeout, quitting...
2024-10-03 11:08:44,413 Worker rq:worker:399b609a43334d0c82603d37cc2a7960: Redis connection timeout, quitting...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1799, in run
    pubsub.get_message(ignore_subscribe_messages=True, timeout=sleep_time)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1690, in get_message
    response = self.parse_response(block=(timeout is None), timeout=timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1542, in parse_response
    response = self._execute(conn, try_read)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1518, in _execute
    return conn.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1520, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1507, in _disconnect_raise_connect
    raise error
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1519, in <lambda>
    lambda: command(*args, **kwargs),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1536, in try_read
    if not conn.can_read(timeout=timeout):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 861, in can_read
    return self._parser.can_read(timeout)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 444, in can_read
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 455, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Traceback (most recent call last):
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/magic/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 202, in start_worker
    start_worker(
  File "/home/magic/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 297, in start_worker
    worker.work(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 456, in work
    self.teardown()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1047, in teardown
    self.unsubscribe()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 624, in unsubscribe
    self.pubsub.unsubscribe()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1659, in unsubscribe
    return self.execute_command("UNSUBSCRIBE", *args)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1479, in execute_command
    self._execute(connection, connection.send_command, *args, **kwargs)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1518, in _execute
    return conn.retry.call_with_retry(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1520, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1507, in _disconnect_raise_connect
    raise error
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1519, in <lambda>
    lambda: command(*args, **kwargs),
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 847, in send_command
    self.send_packed_command(
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 817, in send_packed_command
    self.connect()
  File "/home/magic/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
2024-10-03 11:18:23,468 Worker rq:worker:13bd82c659f44905b98915a080545f1d: Redis connection timeout, quitting...
2024-10-03 11:18:23,505 Worker rq:worker:01470b33157d4849b2a79670d2b54e9d: Redis connection timeout, quitting...
2024-10-03 11:25:11,093 Worker rq:worker:02009faf95174dfbb6a75915c7336ecc: Redis connection timeout, quitting...
2024-10-03 11:25:11,131 Worker rq:worker:60a56cb6ecad43a89c55af3f5832c87c: Redis connection timeout, quitting...
2024-10-03 11:31:59,156 Worker rq:worker:46a2d1560b684870bad34f89b16be096: Redis connection timeout, quitting...
2024-10-03 11:31:59,251 Worker rq:worker:fe93de1faa32475d8d8cb8d533e9a0d2: Redis connection timeout, quitting...
2024-10-03 11:38:49,710 Worker rq:worker:056d1a7097d7491095dc6206105a060b: Redis connection timeout, quitting...
2024-10-03 11:38:49,713 Worker rq:worker:51cada70c93e4f9f8b18e9050e0e7c08: Redis connection timeout, quitting...
2024-10-03 11:45:36,047 Worker rq:worker:c4a67a4052c24faf8eb29cc9ade7277a: Redis connection timeout, quitting...
2024-10-03 11:45:36,055 Worker rq:worker:979abf5da2894bbeb6604d6cbac8df4c: Redis connection timeout, quitting...
2024-10-03 11:52:23,879 Worker rq:worker:d94872ec96aa48e683f7d361567ba47d: Redis connection timeout, quitting...
2024-10-03 11:52:23,940 Worker rq:worker:3acb4da6fbd243a29ce77b9b5d77388a: Redis connection timeout, quitting...
2024-10-03 11:59:05,840 Worker rq:worker:e33894d48fe54762ae92bac9a0904949: Redis connection timeout, quitting...
2024-10-03 11:59:06,484 Worker rq:worker:49ba67b306524f068f7e7d5bdf727a8c: Redis connection timeout, quitting...
2024-10-03 12:05:48,268 Worker rq:worker:27a5a06de35f498ca39db779908c41ad: Redis connection timeout, quitting...
2024-10-03 12:05:49,068 Worker rq:worker:e95824732eda4d699636ce9e88871342: Redis connection timeout, quitting...
2024-10-03 12:12:33,826 Worker rq:worker:da3260e9e54f4423b4d468f4d011d290: Redis connection timeout, quitting...
2024-10-03 12:12:33,826 Worker rq:worker:c78d38c7a2c34c14aeec06b3fde1bb01: Redis connection timeout, quitting...
2024-10-03 12:19:44,589 Worker rq:worker:4db1c269c2864529aaee9d472065a500: Redis connection timeout, quitting...
2024-10-03 12:19:44,589 Worker rq:worker:e34d8800f98b4ea3ab47c9d2babb1343: Redis connection timeout, quitting...
2024-10-03 12:26:37,020 Worker rq:worker:c167aa95e6804976bbe2ff3d5c84ea70: Redis connection timeout, quitting...
2024-10-03 12:26:37,021 Worker rq:worker:d9abcfd32a8244fabb9483f7312f3ca1: Redis connection timeout, quitting...
2024-10-03 12:33:22,325 Worker rq:worker:84c0cfbc440646b4b437414510be2608: Redis connection timeout, quitting...
2024-10-03 12:33:22,397 Worker rq:worker:fc59e1d4c5c84dbcb621383e2d7f7551: Redis connection timeout, quitting...
2024-10-03 12:40:06,319 Worker rq:worker:82a11d6628294ecda0188b5fd800c3e6: Redis connection timeout, quitting...
2024-10-03 12:40:06,366 Worker rq:worker:6112c4faae6d489a9edf6dfddba93c22: Redis connection timeout, quitting...
2024-10-03 12:46:53,971 Worker rq:worker:b9de9e30fa744da09b6ae851aaa0b39f: Redis connection timeout, quitting...
2024-10-03 12:46:53,976 Worker rq:worker:941e3382a3ea4b0585403c3d814e6df1: Redis connection timeout, quitting...
2024-10-03 12:53:38,282 Worker rq:worker:5e76e8d5535040498764f8bc473b46fb: Redis connection timeout, quitting...
2024-10-03 12:53:38,336 Worker rq:worker:aa12e92b3a304b19acca4c72b2bffe07: Redis connection timeout, quitting...
2024-10-03 13:00:23,824 Worker rq:worker:76da1db2da7547a8ba459793d90131c9: Redis connection timeout, quitting...
2024-10-03 13:00:23,876 Worker rq:worker:b7ad9700eec44c3887019ff990f1720e: Redis connection timeout, quitting...
2024-10-03 13:07:08,092 Worker rq:worker:2434c408fb3d4ef284ff6b792c4aff39: Redis connection timeout, quitting...
2024-10-03 13:07:08,148 Worker rq:worker:d03182a109054777a62c0478443e6491: Redis connection timeout, quitting...
2024-10-03 13:18:52,974 Worker rq:worker:5e875056710948b5a011dbeb445c5132: Redis connection timeout, quitting...
2024-10-03 13:18:53,131 Worker rq:worker:6c8996972a7b4484adcca8aa0d4671ab: Redis connection timeout, quitting...
2024-10-03 13:25:36,371 Worker rq:worker:40c0ae83362447e5bf60a52d84abe208: Redis connection timeout, quitting...
2024-10-03 13:25:36,394 Worker rq:worker:30c2a35ea9cd4a96b5beceb6f60a11ed: Redis connection timeout, quitting...
2024-10-03 13:32:19,631 Worker rq:worker:23b96d294e7f4ccfaf0ac802f9a72430: Redis connection timeout, quitting...
2024-10-03 13:32:19,646 Worker rq:worker:be460ce400ab4408a00194a6296de24f: Redis connection timeout, quitting...
2024-10-03 13:38:58,681 Worker rq:worker:162f063c8200435a9630d54802ac0868: Redis connection timeout, quitting...
2024-10-03 13:38:59,438 Worker rq:worker:904097d9e53447e592cf3dd04e1f04af: Redis connection timeout, quitting...
2024-10-03 13:45:42,362 Worker rq:worker:fe00bc1d11434b3bba77dbb46e788d7b: Redis connection timeout, quitting...
2024-10-03 13:45:42,363 Worker rq:worker:89d935264e8b4c61b198e1cc96f39526: Redis connection timeout, quitting...
2024-10-03 13:52:24,598 Worker rq:worker:0bd8410dbff148d985f2c6b2b4685dd6: Redis connection timeout, quitting...
2024-10-03 13:52:24,655 Worker rq:worker:f8508a6fc57c452c965c36f1afbb8abf: Redis connection timeout, quitting...
2024-10-03 13:59:07,498 Worker rq:worker:e58ac0f16e134fb48349ec52099c2e3b: Redis connection timeout, quitting...
2024-10-03 13:59:07,598 Worker rq:worker:e5f0f2673c644e86ac9ff5f58696755c: Redis connection timeout, quitting...
2024-10-03 14:05:51,077 Worker rq:worker:87e0b91788994c5d98425b03f7caa877: Redis connection timeout, quitting...
2024-10-03 14:05:51,105 Worker rq:worker:dc219b04bbe741f29122d4739a71e071: Redis connection timeout, quitting...
2024-10-03 14:12:33,959 Worker rq:worker:420add5c5e0244fabb9aeb35c904d413: Redis connection timeout, quitting...
2024-10-03 14:12:34,051 Worker rq:worker:3f9fc808b4f9417a83db65c9fb991ae1: Redis connection timeout, quitting...
2024-10-03 14:19:20,439 Worker rq:worker:8cf9687da418463098cb90c54d4bb5c9: Redis connection timeout, quitting...
2024-10-03 14:19:20,443 Worker rq:worker:b118de8ba03140709deb52caa696115d: Redis connection timeout, quitting...
2024-10-03 14:26:02,696 Worker rq:worker:434f337164f04d918519ec0568b44547: Redis connection timeout, quitting...
2024-10-03 14:26:02,712 Worker rq:worker:0937f90379cf475aababb6bce0754f87: Redis connection timeout, quitting...
2024-10-03 14:32:44,704 Worker rq:worker:7d9cb8e3962640f9b04b2a48e13abbc6: Redis connection timeout, quitting...
2024-10-03 14:32:44,808 Worker rq:worker:fe87968fb0b74fb18688b13a990443f3: Redis connection timeout, quitting...
2024-10-03 14:39:27,122 Worker rq:worker:ba2b059f2fe34a61b0d7176adcb99af2: Redis connection timeout, quitting...
2024-10-03 14:39:27,133 Worker rq:worker:6c2f7b45f0b04692bee837a5b23db2a6: Redis connection timeout, quitting...
2024-10-03 14:46:07,706 Worker rq:worker:1cb314b88413423caca70e452188be35: Redis connection timeout, quitting...
2024-10-03 14:46:07,805 Worker rq:worker:fda3dbcb65154746aea805c985511f55: Redis connection timeout, quitting...
2024-10-03 14:52:48,436 Worker rq:worker:30a0c550b71b47fd91a4fa52772b2cb2: Redis connection timeout, quitting...
2024-10-03 14:52:48,470 Worker rq:worker:4735979ddb954624b3f8984b4a487397: Redis connection timeout, quitting...
2024-10-03 14:59:29,477 Worker rq:worker:b4a8c7de7493493b986b7da9338404c8: Redis connection timeout, quitting...
2024-10-03 14:59:29,491 Worker rq:worker:a92f7d04a8df43d78fc39abf260173a2: Redis connection timeout, quitting...
2024-10-03 15:06:10,643 Worker rq:worker:7dbdf0486b3f4e3d937490fcd66ee9fd: Redis connection timeout, quitting...
2024-10-03 15:06:10,713 Worker rq:worker:e427d464dea5483fb2abfbde9d17fe38: Redis connection timeout, quitting...
2024-10-03 15:12:50,563 Worker rq:worker:3a51626cc0e84eea9af51351f0d30ba2: Redis connection timeout, quitting...
2024-10-03 15:12:50,590 Worker rq:worker:596e035ed0e84b1092c4206b3af55583: Redis connection timeout, quitting...
2024-10-03 15:19:30,689 Worker rq:worker:b42808c22db1480bb0ea5ad45021538d: Redis connection timeout, quitting...
2024-10-03 15:19:30,699 Worker rq:worker:84161bbe239f4d2bb325b8b11b3f23e2: Redis connection timeout, quitting...
2024-10-03 15:26:10,814 Worker rq:worker:b41494917c1946bba3295d12ad1a94f4: Redis connection timeout, quitting...
2024-10-03 15:26:10,860 Worker rq:worker:e25161cfa5d040629118a0bb606bca78: Redis connection timeout, quitting...
2024-10-03 15:32:50,751 Worker rq:worker:1cc947a8593445b3b0f8829a46bebec9: Redis connection timeout, quitting...
2024-10-03 15:32:50,754 Worker rq:worker:eca3d2e464594fa7a48a6f0b88327072: Redis connection timeout, quitting...
2024-10-03 15:39:28,856 Worker rq:worker:a87ff3cdb2a543b4bf97d72a9670a9cb: Redis connection timeout, quitting...
2024-10-03 15:39:28,874 Worker rq:worker:d79679eaef3941219a62b9fd0d52749d: Redis connection timeout, quitting...
2024-10-03 15:46:05,650 Worker rq:worker:3f4c4df7a1c441648de2fe922c8a9f12: Redis connection timeout, quitting...
2024-10-03 15:46:05,655 Worker rq:worker:e5abe68a274647fba3f84921e429f5be: Redis connection timeout, quitting...
2024-10-03 15:52:40,353 Worker rq:worker:89ceb6f775a14d2ca1b3d3c2b1256519: Redis connection timeout, quitting...
2024-10-03 15:52:41,034 Worker rq:worker:a3e0629766be40b28f0ca5d5a912916e: Redis connection timeout, quitting...
2024-10-03 16:19:29,254 Worker rq:worker:aa5863daa54941089f65c0ae639de3e7: Redis connection timeout, quitting...
2024-10-03 16:19:32,486 Worker rq:worker:3285420d346842cc88eee23b92cd239d: Redis connection timeout, quitting...
2024-10-03 16:26:12,260 Worker rq:worker:fca9104da805479ea867e9575ba17cad: Redis connection timeout, quitting...
2024-10-03 16:26:12,328 Worker rq:worker:ff4f2adb7dd44cf59d417c32cc53a07b: Redis connection timeout, quitting...
2024-10-03 16:32:50,218 Worker rq:worker:c6c66aa0ed554d1e9d3b33d4697fa4cb: Redis connection timeout, quitting...
2024-10-03 16:32:50,266 Worker rq:worker:063e89893f4946ffbf0cae80a790d7b7: Redis connection timeout, quitting...
2024-10-03 16:39:27,935 Worker rq:worker:5892398b4cb1474ca5e3300d2e9d8987: Redis connection timeout, quitting...
2024-10-03 16:39:27,989 Worker rq:worker:01605f9d46a74886b746cd080a858ec8: Redis connection timeout, quitting...
2024-10-03 16:46:06,807 Worker rq:worker:511dbb06d0ce49c5bb9b08db259dba89: Redis connection timeout, quitting...
2024-10-03 16:46:06,824 Worker rq:worker:9ccab108009c46c1bbe681be3e08a9b9: Redis connection timeout, quitting...
2024-10-03 16:52:40,026 Worker rq:worker:8fddf241d2ff4b19ab1339394505fa96: Redis connection timeout, quitting...
2024-10-03 16:52:40,730 Worker rq:worker:72c5bfa193b34229be96294631e2a3c2: Redis connection timeout, quitting...
2024-10-03 16:59:13,694 Worker rq:worker:db0e7c8471314fce90a1e81479ab8fdc: Redis connection timeout, quitting...
2024-10-03 16:59:14,430 Worker rq:worker:a811c015e0f347c0b592360909076e14: Redis connection timeout, quitting...
2024-10-03 17:05:48,894 Worker rq:worker:a752c4f451734eb8b053b7889f9e54f6: Redis connection timeout, quitting...
2024-10-03 17:05:49,533 Worker rq:worker:2001cf5ca43d451fa821cbee879fbf19: Redis connection timeout, quitting...
2024-10-03 17:12:27,152 Worker rq:worker:b0513da4eb534d8080d192c44cd2e420: Redis connection timeout, quitting...
2024-10-03 17:12:27,166 Worker rq:worker:c7ff4c3eddb24de1bb13519459036f7b: Redis connection timeout, quitting...
2024-10-03 17:19:03,130 Worker rq:worker:dc7ac579d62f4c1dafaf798bdb9f9fbf: Redis connection timeout, quitting...
2024-10-03 17:19:03,130 Worker rq:worker:7611822fe82f41cbb332682ea24ca33e: Redis connection timeout, quitting...
2024-10-03 17:25:40,387 Worker rq:worker:fcbd292d1d454fe686c839dc2428a0f5: Redis connection timeout, quitting...
2024-10-03 17:25:40,390 Worker rq:worker:1896bfa6249b487896adb8d71804a85a: Redis connection timeout, quitting...
2024-10-03 17:32:16,479 Worker rq:worker:3c71918d03b7437b9210f6dd497426db: Redis connection timeout, quitting...
2024-10-03 17:32:16,537 Worker rq:worker:55e9065019f844d2a993798bdf5dcf33: Redis connection timeout, quitting...
2024-10-03 17:38:48,339 Worker rq:worker:78380212dea0449bb01fcdaccb80c934: Redis connection timeout, quitting...
2024-10-03 17:38:49,023 Worker rq:worker:f7842baf1eff43a080220d7977107748: Redis connection timeout, quitting...
2024-10-03 17:45:22,590 Worker rq:worker:7a5fe784828a4ab2b16c02e30aaf9dee: Redis connection timeout, quitting...
2024-10-03 17:45:23,147 Worker rq:worker:c9da78266a494b208171433127cf72ad: Redis connection timeout, quitting...
2024-10-03 17:51:54,549 Worker rq:worker:6ba3a55e957d4b18ac0ebb9f77d7cca1: Redis connection timeout, quitting...
2024-10-03 17:51:55,489 Worker rq:worker:ab9d5dcb64574a74b3fde758eb93ebce: Redis connection timeout, quitting...
2024-10-03 17:58:31,251 Worker rq:worker:dfe9e524919442c2917b4402782f2ac0: Redis connection timeout, quitting...
2024-10-03 17:58:31,274 Worker rq:worker:c04e2888db68450cbcb5b629da6bbf5a: Redis connection timeout, quitting...
2024-10-03 18:05:08,725 Worker rq:worker:6510bf538f5a461d967002d7b5008881: Redis connection timeout, quitting...
2024-10-03 18:05:08,803 Worker rq:worker:61709beb3b0449ba8f0788981fe273fb: Redis connection timeout, quitting...
2024-10-03 18:11:46,166 Worker rq:worker:af9e396749c6403d99e5ec29f1b34903: Redis connection timeout, quitting...
2024-10-03 18:11:46,239 Worker rq:worker:b5c1c3bf0a084dd4968b4922fc33a212: Redis connection timeout, quitting...
2024-10-03 18:18:16,976 Worker rq:worker:d95b181b38154e929f2c47d4f6d3541a: Redis connection timeout, quitting...
2024-10-03 18:18:17,515 Worker rq:worker:c15073ff015d43c7b65ccfee348f4114: Redis connection timeout, quitting...
2024-10-03 18:24:59,589 Worker rq:worker:d6ef04d671074d509f2fd43cfe0c71c1: Redis connection timeout, quitting...
2024-10-03 18:25:00,284 Worker rq:worker:8d9b3023f97643cb8b9a1cd81876a8ac: Redis connection timeout, quitting...
2024-10-03 18:32:03,809 Worker rq:worker:c98c73a14bad4a978bd40eedda75400b: Redis connection timeout, quitting...
2024-10-03 18:32:06,033 Worker rq:worker:aa9a8d5a32c44cbeb6297dec05815b6a: Redis connection timeout, quitting...
2024-10-03 22:44:16,510 Worker rq:worker:5269a20da7c0472799b32a6881c202aa: Redis connection timeout, quitting...
2024-10-03 22:50:52,081 Worker rq:worker:7b853911ba244351b4b17872d16b360a: Redis connection timeout, quitting...
